Make decisions is implemented
se2-game-of-life/backend pull request #39
Opened 2024-05-24 19:21 UTC by J0hanna01

2024-05-25 12:22 UTC, thomas-schleicher requested changes

2024-05-25 12:22 UTC, thomas-schleicher commented on src/main/java/se/group3/backend/repositories/HouseCardRepository.java
> +
The repository dose not need to interact with the player, change the method to take the amount of money you want to compare against as a parameter instead of passing the game service

2024-05-25 18:35 UTC, J0hanna01 commented on src/main/java/se/group3/backend/repositories/HouseCardRepository.java
> +
Thanks you are absolutely right! :)

2024-05-26 08:33 UTC, thomas-schleicher requested changes

2024-05-26 08:33 UTC, thomas-schleicher commented on src/main/java/se/group3/backend/services/GameService.java
> +        }
der player muss aus der queue raus genommen werden, sonst kommt der halt immer wieder an den zug, und wenn der letzte spieler retiered muss das spiel stoppen (das würd ich zumindest als todo dazu schreiben)

2024-05-26 09:11 UTC, thomas-schleicher approved these changes

2024-05-26 09:14 UTC, Haxe33 approved these changes
lgtm

2024-05-26 09:14 UTC, merged