Teleport cell
se2-game-of-life/backend pull request #49
Opened 2024-06-12 16:52 UTC by nzhurat

2024-06-12 19:29 UTC, Haxe33 requested changes

2024-06-12 19:29 UTC, Haxe33 commented on src/main/java/se/group3/backend/services/GameService.java
> +                    break;
Actually there are a few points here:

- make sure after a case to call the next player
- teleport isnt just +2, maybe teleport to another teleport cell, but dont skip any decission fields, cause they are very important to the game flow
- why do you neet choose left here?

Just push your commits when your done :)

2024-06-13 12:19 UTC, nzhurat commented on src/main/java/se/group3/backend/services/GameService.java
> +                    break;
I handled next turn. ChooseLeft i need to know whether the plyer wants to teleport or no. It is just two cells so even if player skips it i don´t think it will affect the game too much. And this TELEPORT cells wilL be only in 3 places on the board.

2024-06-14 08:56 UTC, J0hanna01 commented on src/main/java/se/group3/backend/services/GameService.java
> +                    break;
I think Florian is right. Always +2 could be a problem, if you look up how we made the decisions paths. For example +2 in college path could lead you to the beginning of career path... Please think about that. Also the stop cells are kinda a very important topic in the game. If you teleport +2 then the player always comes on the "yes" path and doesn't pay the 50k... 

So if I understand it correctly you want the player to decide if he wants to teleport or not? 
Also please make yourself familiar with the cell logic in backend. You can't just add the teleport cell to makeDecision, because you need to add it also to handleCell, where you need to set the hasDesicion variable of lobby on true...  Just write me on Whatsapp or Discord if you have any questions. :)

2024-06-14 08:58 UTC, Haxe33 commented on src/main/java/se/group3/backend/services/GameService.java
> +                    break;
It would affect the game a lot, if a player skips a decission field, because they are the key component of the game.
If there are only 3 of them, please put them in the plan we have in discord and if we all agree to them you can add them into the database, but please wait for aprovel for that, cause you could brake the whole game if these cells are on the wrong possitions.

2024-06-14 09:00 UTC, J0hanna01 requested changes
Pls check the comments :)

2024-06-15 17:26 UTC, closed without merging